### ISSUE TITLE
Update to react tools version 0.13.3

### ISSUE THREAD

**Issue by nicolls1** [brunch/react-brunch#13]
I see #8 but I don't see how to do it anywhere? Do you have to use shrinkwrap? is there an example of this?

**Comment by denysdovhan** [comment]
@nicolls1 hey, thanks for reporting!

This plugin is going to be deprecated. Now it's better to use [`babel-brunch`](https://github.com/babel/babel-brunch) with [`babel-preset-react`](https://github.com/babel/babel/tree/master/packages/babel-preset-react). Take a look at [`with-react`](https://github.com/brunch/with-react) skeleton for inspiration.

Please update!
